language: rust
sudo: false
rust: nightly

install: cargo install mdbook
script: cd reference && mdbook build && mdbook test
deploy:
  provider: script
  script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd book && RUST_BACKTRACE=1 ../rust_out)
  skip_cleanup: true
  keep-history: false
  on:
    branch: master
